spring:
  datasource:
    url: jdbc:h2:mem:movimentacao;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

logging:
  level:
    root: WARN

movimentacao:
  kafka:
    enabled: false
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    topics:
      movimentacao-criada: movimentacao.criada.test
      movimentacao-atualizada: movimentacao.atualizada.test
